sudo: required
dist: trusty

language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8

script:
- sbt compile test it:test pt:test unidoc
- ls -l
- sudo chown -R travis:travis /home/travis
- ls -l
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./sbt
  "gitPublish target/javaunidoc https://$GH_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git
  javadoc sphere-oss automation@commercetools.de"; fi

notifications:
  email:
    on_success: never
    on_failure: change
